# Generated by Django 3.1.1 on 2022-03-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SSC', models.CharField(max_length=3)),
                ('HSC', models.CharField(max_length=3)),
                ('Phy', models.CharField(max_length=3)),
                ('Chem', models.CharField(max_length=3)),
                ('Bio', models.CharField(max_length=3)),
                ('Maths', models.CharField(max_length=3)),
                ('hrs', models.CharField(max_length=2)),
                ('CreativeThink', models.CharField(max_length=2)),
                ('SelfLearn', models.CharField(max_length=2)),
                ('Coding', models.CharField(max_length=2)),
                ('Pubskill', models.CharField(max_length=2)),
                ('ReadWrite', models.CharField(max_length=2)),
            ],
        ),
    ]
