# Generated by Django 3.1.1 on 2022-03-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Comp',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='contact',
            name='Extracurr',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='contact',
            name='Finance',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='contact',
            name='Gender',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='contact',
            name='HWSW',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='contact',
            name='Literacy',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='contact',
            name='Living',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='contact',
            name='NatureWork',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='contact',
            name='Sports',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='contact',
            name='Subject',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='contact',
            name='Teams',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='contact',
            name='gap',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Bio',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Chem',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Coding',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='contact',
            name='CreativeThink',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='contact',
            name='HSC',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Maths',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Phy',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Pubskill',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='contact',
            name='ReadWrite',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='contact',
            name='SSC',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='contact',
            name='SelfLearn',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='contact',
            name='hrs',
            field=models.CharField(default='', max_length=2),
        ),
    ]
